"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_state
"""

right_format = """
$cmd_duration\
$python
"""

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[directory]
style = "#00a2dc bold"
format = "[ $path]($style) "
truncation_length = 8
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "bold #4e9a06"
format ="[$symbol$branch(:$remote_branch)]($style) "

[python]
format = '[(\($virtualenv\) )]($style)'
style = "black bold"
